version: 2
updates:
  - package-ecosystem: pip
    open-pull-requests-limit: 99
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 99
    directory: "/"
    schedule:
      interval: weekly
